[package]
name = "consensus"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
tracing-subscriber =  "0.2"
tracing = "0.1"
dusk-bls12_381-sign = "0.4.0"
rand_core = { version = "0.5.1", default-features = false }
sha3 = {version = "0.10.2"}
num-bigint = {version = "0.4.3", default-features = false}

[dev-dependencies]
rand = { version = "0.8", default-features = false, features = ["std_rng"] }
hex-literal = {version = "0.3.4"}


[[example]]
name = "testbed"
path = "example/main.rs"
